Repository goatcorp/DalamudPlugins, pull requests merged in 2022-07, with the labels that each got.

#2414 [Testing] Oh gee, CD
  testing/OhGeeCD/OhGeeCD.json
  testing/OhGeeCD/images/icon.png
  testing/OhGeeCD/latest.zip
Labels: new plugin, code reviewed, rules reviewed, combat plugin

#2796 [Testing] Add KikoGuide
  testing/KikoGuide/KikoGuide.json
  testing/KikoGuide/images/icon.png
  testing/KikoGuide/latest.zip
Labels: new plugin, code reviewed

#2618 [Testing] EnemyListHP
  testing/EnemyListHP/EnmityHp.json
  testing/EnemyListHP/images/icon.png
  testing/EnemyListHP/latest.zip
Labels: new plugin, code reviewed

#2791 [Testing] InventorySearchBar
  testing/InventorySearchBar/InventorySearchBar.json
  testing/InventorySearchBar/images/icon.png
  testing/InventorySearchBar/latest.zip
Labels: new plugin

#2804 [Testing] Add Coin Pouch
  testing/CoinPouch/CoinPouch.json
  testing/CoinPouch/images/icon.png
  testing/CoinPouch/latest.zip
Labels: new plugin

#2821 Neko Fans
  testing/Neko/Neko.json
  testing/Neko/images/icon.png
  testing/Neko/latest.zip
Labels: new plugin
