Repository goatcorp/DalamudPlugins, pull requests merged in 2022-05, with the labels that each got.

#2407 [Testing] SkillDisplay 0.0.0.2
  testing/SkillDisplay/SkillDisplay.json
  testing/SkillDisplay/latest.zip
Labels: new plugin

#2391 [Testing] Say What? 0.9.1.0
  testing/WhatDidYouSay/WhatDidYouSay.json
  testing/WhatDidYouSay/images/image1.png
  testing/WhatDidYouSay/images/image2.png
  testing/WhatDidYouSay/latest.zip
Labels: new plugin

#2254 [Testing] AutoTranslateXIV 1.0.0.0
  testing/AutoTranslateXIV/AutoTranslateXIV.json
  testing/AutoTranslateXIV/images/icon.png
  testing/AutoTranslateXIV/latest.zip
Labels: new plugin

#2385 [TESTING] New: Gearset Helper Plugin v1.3.0.0
  testing/GearsetHelperPlugin/GearsetHelperPlugin.json
  testing/GearsetHelperPlugin/images/icon.png
  testing/GearsetHelperPlugin/images/image1.png
  testing/GearsetHelperPlugin/images/image2.png
  testing/GearsetHelperPlugin/latest.zip
Labels: new plugin

#2544 [Testing] CrossUp
  testing/CrossUp/CrossUp.json
  testing/CrossUp/images/icon.png
  testing/CrossUp/latest.zip
Labels: new plugin

#2253 [Testing] Distance 0.9.5.0
  testing/Distance/Distance.json
  testing/Distance/images/icon.png
  testing/Distance/images/image1.png
  testing/Distance/latest.zip
Labels: new plugin, code reviewed, rules reviewed, combat plugin

#2551 [Testing] New Plugin: Desynthesis 2
  testing/DesynthesisTwo/DesynthesisTwo.json
  testing/DesynthesisTwo/latest.zip
Labels: new plugin, rules reviewed

#2489 Fullscreen Toggle plugin
  plugins/FullscreenToggle/FullscreenToggle.json
  plugins/FullscreenToggle/images/icon.png
  plugins/FullscreenToggle/latest.zip
Labels: new plugin, rules reviewed

#2542 [Testing] MBHistory
  testing/MBHistory/MBHistory.json
  testing/MBHistory/images/icon.png
  testing/MBHistory/latest.zip
Labels: new plugin, rules reviewed

#2556 [Testing] Death Roll Helper
  testing/DeathRoll/DeathRoll.json
  testing/DeathRoll/images/icon.png
  testing/DeathRoll/latest.zip
Labels: new plugin

#2497 [Testing] A Realm Recorded v0.4.0.0
  testing/ARealmRecorded/ARealmRecorded.json
  testing/ARealmRecorded/images/icon.png
  testing/ARealmRecorded/latest.zip
Labels: new plugin
