Repository goatcorp/DalamudPlugins, pull requests merged in 2022-06, with the labels that each got.

#2592 Update KingdomHeartsPlugin to 1.0.5.0.
  plugins/KingdomHeartsPlugin/KingdomHeartsPlugin.json
  plugins/KingdomHeartsPlugin/latest.zip
Labels: needs additional review

#2482 [Testing] Target Furniture 1.0.1.2
  testing/TargetFurniture/TargetFurniture.json
  testing/TargetFurniture/images/icon.png
  testing/TargetFurniture/images/image1.png
  testing/TargetFurniture/latest.zip
Labels: new plugin, code reviewed, rules reviewed

#2358 Add HighFpsPhysicsPlugin to test.
  testing/HighFpsPhysicsPlugin/HighFpsPhysicsPlugin.json
  testing/HighFpsPhysicsPlugin/latest.zip
Labels: new plugin, code reviewed, rules reviewed

#2634 [Testing] StackSellPrice
  plugins/StackSellPrice/StackSellPrice.json
  plugins/StackSellPrice/images/icon.png
  plugins/StackSellPrice/latest.zip
Labels: new plugin, code reviewed

#2642 [New Plugin] Audible Character Status 1.0.0.0
  plugins/AudibleCharacterStatus/AudibleCharacterStatus.json
  plugins/AudibleCharacterStatus/images/icon.png
  plugins/AudibleCharacterStatus/latest.zip
Labels: new plugin, code reviewed

#2488 [Testing] MimicryHelper 1.0.0.0
  testing/MimicryHelper/MimicryHelper.json
  testing/MimicryHelper/images/icon.png
  testing/MimicryHelper/latest.zip
Labels: new plugin, code reviewed, combat plugin, needs additional review

#2666 PlayerTags v1.3
  plugins/PlayerTags/PlayerTags.json
  plugins/PlayerTags/images/icon.png
  plugins/PlayerTags/images/image1.png
  plugins/PlayerTags/images/image2.png
  plugins/PlayerTags/latest.zip
Labels: code reviewed, rules reviewed, needs additional review
